version: 2
jobs:
  build:

    branches:
      only:
        - master 

    docker:
      - image: circleci/python:3.7.1
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps:

      - checkout # checkout src code to working dir

      - run:
          name: install PyGran.analysis deps
          command: |
            pip3 install --upgrade pip --user
            pip3 install -e .[extra] --user

      - run:
          name: install PyGran.analysis
          command: |
            pip3 install . --user

      - run:
          name: run tests
          command: |
            python3 -m pytest --cov  tests/pytest/test_analysis --trajf "DEM_flow/traj/particles*.dump"
            python3 -m codecov

      - store_test_results:
          path: .
